language: php
php:
  - '5.6'
  - '7.0'
before_install :
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar

script : phpunit --configuration database/socialnetworkdataset.xml tests/ --coverage-clover build/logs/clover.xml